version: '3'
services:
  web:
    container_name: "${PROJECT}"
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node
      - /home/node/node_modules
    links:
      - mongo
  mongo:
    container_name: "${PROJECT}_mongo"
    image: mongo
    restart: always
    env_file: .env
  mongo-express:
    container_name: "${PROJECT}_mongo_express"
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
